# -*- coding: utf-8 -*-
"""Metodologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PHtWNI8HGRI4SNEhU4FxetbepA8fxE9
"""

# Simulação: executar testes automaticamente (representação simples)

# Exemplo de implementação da função calcular_desconto
def calcular_desconto(valor, percentual_desconto):
    """Calcula o valor com desconto."""
    desconto = valor * (percentual_desconto / 100)
    return valor - desconto

# Exemplo de implementação da função verificar_nome_usuario
def verificar_nome_usuario(nome):
    """Verifica se o nome de usuário não está vazio."""
    if not nome:
        return "Erro: Nome é obrigatório."
    return "Nome válido." # Ou qualquer outra mensagem de sucesso

def rodar_todos_os_testes():
    test_1 = calcular_desconto(100, 10) == 90
    test_2 = verificar_nome_usuario("") == "Erro: Nome é obrigatório."
    return test_1 and test_2

if rodar_todos_os_testes():
    print("Todos os testes passaram. Pronto para deploy!")
else:
    print("Alguns testes falharam.")


#Saída: 
    #Todos os testes passaram. Pronto para deploy!
