# -*- coding: utf-8 -*-
"""TesteIntegracao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDWfs3uqSlp3lk5NTbA9GATQ3AO1hMt2
"""

# test_api_integracao.py
import requests
import pytest

BASE_URL = "https://jsonplaceholder.typicode.com"

def test_consulta_posts():
    response = requests.get(f"{BASE_URL}/posts/1")
    assert response.status_code == 200
    assert "userId" in response.json()